name: Flutter CI

on:
  push:
    branches: [ main ] # main ブランチへの push でトリガー
  pull_request:
    branches: [ main ] # main ブランチへの Pull Request でトリガー

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Flutter SDK のセットアップ
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # 使用する Flutter のバージョンを指定 (適宜変更)
          channel: 'stable'
          cache: true # 依存関係のキャッシュを有効にする

      # 依存関係の取得
      - name: Get dependencies
        working-directory: ./mobile
        run: flutter pub get

      # コードフォーマットのチェック (オプション)
      # - name: Check formatting
      #   working-directory: ./mobile
      #   run: dart format --output=none --set-exit-if-changed .

      # 静的解析
      - name: Analyze project dependencies
        working-directory: ./mobile
        run: flutter analyze

      # テストの実行
      - name: Run tests
        working-directory: ./mobile
        run: flutter test
